### ISSUE TITLE
Private git Ansible collections

### ISSUE THREAD

**Issue by D1StrX** [shadowman-lab/Ansible-PAH#3]
Saw your video regarding ansible-builder v3. Was wondering how to securely use ssh auth for private git repos that contain Ansible collections. 

```yaml
# requirements.yml
  - name: git@<url>.git
     type: git
     version: <branch>
```

Adding the ssh files to /root/.ssh and cleaning up afterwards seems to do the trick.
